
import 'package:get/get.dart';
import 'package:hotel_management/app/data/models/hotel_name_model.dart';
import 'package:hotel_management/app/ui/utils/image_url.dart';

class HotelNameController {
  RxList <HotelNameModel> hotelNameList = <HotelNameModel> [
    HotelNameModel(name: "Mountain Shade Resort",
        image: ImageUrl.threeStar,
        rated:4.5,
        price: "\$360"),
    HotelNameModel(name: "Ivory Orchid Hotel",
        image: ImageUrl.fourStar,
        rated:3.5,
        price: "\$300"),
    HotelNameModel(name: "Cascade Haven",
        image: ImageUrl.hotelFour,
        rated:3.5,
        price: "\$200"),
    HotelNameModel(name: "Aurora Suites",
        image: ImageUrl.hotelTwo,
        rated:4,
        price: "\$350"),
    HotelNameModel(name: "Ivory Orchid Hotel",
        image: ImageUrl.hotelOne,
        rated:4.5,
        price: "\$300"),
    HotelNameModel(name: "Aurora Suites",
        image: ImageUrl.hotelTwo,
        rated:4,
        price: "\$350"),
    HotelNameModel(name: "Majestic Grove",
        image: ImageUrl.hotelThree,
        rated:5,
        price: "\$400"),
    HotelNameModel(name: "Cascade Haven",
        image: ImageUrl.hotelFour,
        rated:3.5,
        price: "\$200"),
    HotelNameModel(name: "Ivory Orchid Hotel",
        image: ImageUrl.hotelFive,
        rated:5,
        price: "\$380"),
    HotelNameModel(name: "Pulse Suites",
        image: ImageUrl.hotelSix,
        rated:4.5,
        price: "\$300"),
    HotelNameModel(name: "Mountain Shade Resort",
        image: ImageUrl.roomOne,
        rated:4,
        price: "\$360"),
    HotelNameModel(name: "Ivory Orchid Hotel",
        image: ImageUrl.roomTwo,
        rated:4.5,
        price: "\$300"),
  ].obs;
}